// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restaurant.Services.ProductAPI.Data.Contexts;

#nullable disable

namespace Restaurant.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240125134345_mig1")]
    partial class mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Restaurant.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripton_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName_EN = "Appetizer",
                            CategoryName_TR = "Aperatif",
                            CreatedDate = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description_TR = "Samosa, Hint mutfağına ait geleneksel bir atıştırmalık veya çeşitli yemeklerde bir yan lezzet olarak sıkça bulunan bir hamur işidir. ",
                            Descripton_EN = "Quisque vel lacus ac magna, vehicula sagittis ut non lacus.<br/> Vestibulum arcu turpis, maximus malesuada neque. Phasellus commodo cursus pretium.",
                            ImageUrl = "https://placehold.co/603x403",
                            Name_EN = "Samosa",
                            Name_TR = "Samosa",
                            Price = 15.0,
                            UpdatedDate = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CategoryName_EN = "Side dish",
                            CategoryName_TR = "Yan yemek",
                            CreatedDate = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description_TR = "Pirinç, dünya genelinde yaygın olarak tüketilen temel bir tahıl ürünüdür.<br/> Pirinç, çeşitli yemeklerin temel malzemelerinden biridir ve birçok kültürde ana öğünlerde veya yan yemek olarak kullanılır.",
                            Descripton_EN = " Rice is a fundamental cereal grain widely consumed worldwide.<br/> It serves as a staple ingredient in various dishes and is used as a primary component in many cultures for main meals or as a side dish. ",
                            ImageUrl = "https://placehold.co/603x403",
                            Name_EN = "Rice",
                            Name_TR = "Pilav",
                            Price = 14.5,
                            UpdatedDate = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CategoryName_EN = "Main dish",
                            CategoryName_TR = "Ana yemek",
                            CreatedDate = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description_TR = "Bu tarifte, tavuk butları, taze narenciye suyu bazlı bir sosta marine edilip fırında pişirilir. <br/> Tavuklar, yumuşak ve sulu olana kadar pişirildikten sonra yanında fırınlanmış sebzelerle servis edilir. <br/> Bu tarif, taze ve ferah lezzetleri bir araya getirirken sağlıklı ve doyurucu bir ana yemek sunar.",
                            Descripton_EN = "In this recipe, chicken thighs are marinated with a glaze made from fresh citrus juice and then baked in the oven.<br/> Once the chicken is cooked to tender and juicy perfection, it is served with a side of roasted vegetables.<br/> This dish brings together the bright and refreshing flavors while offering a healthy and satisfying main course.",
                            ImageUrl = "https://placehold.co/603x403",
                            Name_EN = "Citrus Glazed Chicken with Roasted Vegetables",
                            Name_TR = "Narenciye Soslu Tavuk ve Fırınlanmış Sebzeler",
                            Price = 14.5,
                            UpdatedDate = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
